---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/new_projects.json
  label: New projects
- type: document
  path: data/products.json
  label: Products
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.53'
